name: Build React Application

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - uses: marceloprado/has-changed-path@v1.0.1
      id: changed-client
      with:
        paths: client/
      

    - name: Use Node.js ${{ matrix.node-version }}
      if: steps.changed-front.outputs.changed == 'true'
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup
      if: steps.changed-front.outputs.changed == 'true'
      run: |
        cd client/
        npm ci

    - name: Build
      if: steps.changed-front.outputs.changed == 'true'
      run: |
        cd client/
        npm run build
        cd ..

    - name: Re-push
      if: steps.changed-front.outputs.changed == 'true'
      run: |
        git config --global user.email "richardr1126@gmail.com"
        git config --global user.name "Richard Roberson"
        git add .
        git commit -m "Updated build"
        git push





